# Generated by Django 2.2.5 on 2019-10-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_slogan', models.CharField(max_length=100)),
                ('site_author', models.CharField(max_length=100)),
            ],
        ),
    ]
