# Generated by Django 2.2.5 on 2019-10-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageWorker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_a', models.CharField(max_length=100)),
                ('site_b', models.CharField(max_length=100)),
                ('site_c', models.CharField(max_length=100)),
                ('site_d', models.CharField(max_length=100)),
                ('site_e', models.CharField(max_length=100)),
                ('site_f', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='site_info',
            name='site_a',
        ),
        migrations.RemoveField(
            model_name='site_info',
            name='site_b',
        ),
        migrations.RemoveField(
            model_name='site_info',
            name='site_c',
        ),
    ]
