# Generated by Django 2.2.5 on 2019-10-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageWorker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_info',
            name='site_name',
            field=models.CharField(max_length=100, verbose_name='date published'),
        ),
    ]
