# Generated by Django 2.2.5 on 2019-10-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageWorker', '0003_auto_20191023_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
