# Generated by Django 2.2.5 on 2019-10-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageWorker', '0004_category_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
