# Generated by Django 2.2.5 on 2019-10-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageWorker', '0005_auto_20191028_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_info',
            name='site_a',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='site_info',
            name='site_b',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='site_info',
            name='site_c',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
