# Generated by Django 2.2.5 on 2019-10-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageWorker', '0006_auto_20191028_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_info',
            name='site_a',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='site_info',
            name='site_b',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='site_info',
            name='site_c',
            field=models.CharField(max_length=100),
        ),
    ]
